server:
  port: 8982
#logging:
#  file:
#    name: flow.log
logging:
  file:
    name: flow.log
  level:
    com:
       checkmarx: DEBUG
    org:
       apache:
          http:
             wire: DEBUG
       springframework:
          web:
             client:
               RestTemplate: DEBUG
               
cxflow:
  #bug-tracker: GitHub
  bug-tracker: Jira
  bug-tracker-impl:
  #  - GitHub
    - Jira
  branches:
    - main
    - branch1
  filter-severity:
  #  - High
  filter-category:
  #  - SQL_Injection
  #  - Stored_XSS
  #  - Reflected_XSS_All_Clients
  filter-cwe:
  filter-status:
  #mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  #wiki-url: https://custodela.atlassian.net/wiki/spaces/AS/pages/79462432/Remediation+Guidance
  codebash-url: https://checkmarx-demo.codebashing.com/courses/

checkmarx:
  version: 9.0
  username: admin
  password: KsHPJ8JCD5otOLixmMov_
  client-id: resource_owner_client
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  scope: access_control_api sast_rest_api
  base-url: http://ec2amaz-3tsivek/
  team: /CxServer
  url: ${checkmarx.base-url}/cxrestapi
  multi-tenant: false
  #WSDL Config
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  sdk-url: ${checkmarx.base-url}/cxwebinterface/SDK/CxSDKWebService.asmx
  portal-wsdl: ${checkmarx.base-url}/Portal/CxWebService.asmx?wsdl
  sdk-wsdl: ${checkmarx.base-url}/SDK/CxSDKWebService.asmx?wsdl

github:
  webhook-token: 12345
  token: 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
  url: https://github.com
  api-url: https://api.github.com/repos/
  false-positive-label: false-positive
  block-merge: true
  

jira:
   url: https://lmgarciaviejo.atlassian.net
   username: lmgarciaviejo@gmail.com
   token: uqDOLvWhDE1xvSHCigEq8EAE
   project: CXSAS
   issue-type: Bug
   label-prefix: CX
   priorities:
     High: Highest
     Medium: Medium
     Low: Low
     Informational: Lowest
   open-transition: LGV_Reopen
   close-transition: LGV_Close
   open-status:
     - To Do
     - In Progress
   closed-status:
     - Done
   fields:
     - type: result
       name: cwe
       jira-field-name: CWEs
       jira-field-type: label
     - type: result
       name: category
       jira-field-name: Category
       jira-field-type: label
     - type: static
       name: not needed1
       jira-field-name: StaticField
       jira-field-type: text
       jira-default-value: Hola
     - type: static
       name: not needed2
       jira-field-name: MyDropDown
       jira-field-type: single-select
       jira-default-value: Option LGV2
